using UnityEngine;

public class PlayerStateFlagScript : MonoBehaviour
{
    [SerializeField]
    private int playerNumber = 1; // 僾儗僀儎乕斣崋

    //void Start()
    //{
    //    playerBase1.ChangeState(PlayerState.enLocalPlayerTurn); // 僾儗僀儎乕1偺忬懺傪儘乕僇儖僾儗僀儎乕僞乕儞偵愝掕
    //    playerBase2.ChangeState(PlayerState.enOtherPlayerTurn); // 僾儗僀儎乕2偺忬懺傪懠偺僾儗僀儎乕僞乕儞偵愝掕
    //    playerBase3.ChangeState(PlayerState.enOtherPlayerTurn); // 僾儗僀儎乕3偺忬懺傪懠偺僾儗僀儎乕僞乕儞偵愝掕
    //    playerBase4.ChangeState(PlayerState.enOtherPlayerTurn); // 僾儗僀儎乕4偺忬懺傪懠偺僾儗僀儎乕僞乕儞偵愝掕
    //}

    //void CheckStatus()
    //{
    //    // TODO:hayasi 壗偐偟傜僼儔僌傪捛壛偟側偄偲僎乕儉奐巒憗乆屇偽傟傞丅棟憐偼僉儍儔僋僞乕傪憖嶌偟巭傑偭偨帪傪庢摼偟側偄偲偄偗側偄丅
    //    if (playerMove1.GetIsStop())
    //    {
    //        playerBase2.ChangeState(PlayerState.enLocalPlayerTurn);
    //        // 僾儗僀儎乕1偺忬懺傪僠僃僢僋
    //        if (enemyTurnCount.EnemyTurnCount <= 0)
    //        {
    //            playerBase1.ChangeState(PlayerState.enEnemyTurn);
    //            Debug.Log("僾儗僀儎乕1偺忬懺傪揋偺僞乕儞偵曄峏偟傑偟偨丅");
    //        }
    //        else
    //        {
    //            playerBase1.ChangeState(PlayerState.enOtherPlayerTurn);
    //            Debug.Log("僾儗僀儎乕1偺忬懺傪懠偺僾儗僀儎乕僞乕儞偵曄峏偟傑偟偨丅");
    //        }
    //    }
    //    else
    //    {
    //        playerBase1.ChangeState(PlayerState.enLocalPlayerTurn);
    //    }


    //    if (playerMove2.GetIsStop())
    //    {
    //        if (enemyTurnCount.EnemyTurnCount <= 0)
    //        {
    //            playerBase2.ChangeState(PlayerState.enEnemyTurn);
    //        }
    //        else
    //        {
    //            playerBase2.ChangeState(PlayerState.enOtherPlayerTurn);
    //        }
    //    }

    //    else
    //    {
    //        playerBase2.ChangeState(PlayerState.enLocalPlayerTurn);
    //    }

    //    if (playerMove3.GetIsStop())
    //    {
    //        if (enemyTurnCount.EnemyTurnCount <= 0)
    //        {
    //            playerBase3.ChangeState(PlayerState.enEnemyTurn);
    //        }
    //        else
    //        {
    //            playerBase3.ChangeState(PlayerState.enOtherPlayerTurn);
    //        }
    //    }

    //    else
    //    {
    //        playerBase3.ChangeState(PlayerState.enLocalPlayerTurn);
    //    }

    //    if (playerMove4.GetIsStop())
    //    {
    //        if (enemyTurnCount.EnemyTurnCount <= 0)
    //        {
    //            playerBase4.ChangeState(PlayerState.enEnemyTurn);
    //        }
    //        else
    //        {
    //            playerBase4.ChangeState(PlayerState.enOtherPlayerTurn);
    //        }
    //    }

    //    else
    //    {
    //        playerBase4.ChangeState(PlayerState.enLocalPlayerTurn);
    //    }

    //}

    //// Update is called once per frame
    //void Update()
    //{
    //    CheckStatus(); // 僾儗僀儎乕偺忬懺傪僠僃僢僋
    //}
}
